name: temp
description: boilerplate from minhminh

version: 1.0.0+1

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  
  # Common
  get: ^4.6.3
  equatable: ^2.0.5
  flutter_bloc: ^8.1.2
  flutter_screenutil: ^5.5.4
  get_storage: ^2.0.3
  overlay_support: ^2.0.0
  #  Network
  dio: ^4.0.6
  connectivity_plus: ^3.0.3
  logger: ^1.1.0

  # Notification
  flutter_local_notifications: ^9.9.1-dev.2
  firebase_messaging: ^14.2.0

  # Firebase
  firebase_core: ^2.4.0
  firebase_auth: ^4.2.3

  # Login social
  google_sign_in: ^6.0.2
  flutter_facebook_auth: ^5.0.7
  zalo_flutter: ^0.0.5
  sign_in_with_apple: ^4.3.0

  #Other
  pin_code_fields: ^7.4.0
  animations: ^2.0.3
  smooth_page_indicator: ^1.0.0+2
  carousel_slider: ^4.1.1
  flutter_widget_from_html_core: ^0.8.5+3
  shimmer: ^2.0.0
  modal_bottom_sheet: ^2.0.1
  device_info: ^2.0.3
  flutter_spinkit: ^5.1.0
  keyboard_dismisser: ^3.0.0
  flutter_keyboard_visibility: ^5.2.0
  hive: ^2.2.3
  cached_network_image: ^3.2.2
  flutter_svg: ^1.1.5
  image_picker: ^0.8.5+3
  image_cropper: ^3.0.0


dev_dependencies:
  flutter_launcher_icons: ^0.10.0
  flutter_lints: ^2.0.1

flutter_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/images/png/logo_1024.png"

jsonToDart:
  typeChecking: true  #default: undefined (Select from picker)
  nullValueDataType: dynamic #default: dynamic
  nullSafety: true #default: false
  copyWithMethod: false #default: false
  mergeArrayApproach: false #default: true 

flutter:
  uses-material-design: true
  assets:
    - assets/images/ 
